Update test pipelines and support pg18 in all workflows (#351)
* Add reusable gateway template and support pg18 in pipelines

Signed-off-by: Shuai Tian <shuaitian@microsoft.com>

* fix

Signed-off-by: Shuai Tian <shuaitian@microsoft.com>

* workflows must be defined at the top level of the .github/workflows/ directory

Signed-off-by: Shuai Tian <shuaitian@microsoft.com>

* format

Signed-off-by: Shuai Tian <shuaitian@microsoft.com>

* fix version

Signed-off-by: Shuai Tian <shuaitian@microsoft.com>

* Add guards for PostgreSQL 18 macros in RUM index definitions

Signed-off-by: Shuai Tian <shuaitian@microsoft.com>

* RumPostingItem in pg18

Signed-off-by: Shuai Tian <shuaitian@microsoft.com>

* don't install public rum for pg18

Signed-off-by: Shuai Tian <shuaitian@microsoft.com>

* fix build errors

Signed-off-by: Shuai Tian <shuaitian@microsoft.com>

* fix rum requires for rpm

Signed-off-by: Shuai Tian <shuaitian@microsoft.com>

* use postgis36

Signed-off-by: Shuai Tian <shuaitian@microsoft.com>

* skip distributed tests for PG18 as citus not supported yet

Signed-off-by: Shuai Tian <shuaitian@microsoft.com>

* use script for install instead of template

Signed-off-by: Shuai Tian <shuaitian@microsoft.com>

* fix build

Signed-off-by: Shuai Tian <shuaitian@microsoft.com>

* always run reduced matrix

Signed-off-by: Shuai Tian <shuaitian@microsoft.com>

* fix changelog copy script

Signed-off-by: Shuai Tian <shuaitian@microsoft.com>

* fix indent

Signed-off-by: Shuai Tian <shuaitian@microsoft.com>

---------

Signed-off-by: Shuai Tian <shuaitian@microsoft.com>

diff --git a/.github/workflows/regress_tests.yml b/.github/workflows/regress_tests.yml
--- a/.github/workflows/regress_tests.yml
+++ b/.github/workflows/regress_tests.yml
@@ -21,8 +21,9 @@ on:
       - '*.md'
 
 jobs:
-  test-pr:
-    if: github.event_name == 'pull_request' && github.event.pull_request.draft == false
+  DocumentDB-unit-tests:
+    runs-on: ${{ matrix.runner }}
+    name: SQL tests on ${{ matrix.arch }} with PG${{ matrix.pg_version }}
     strategy:
       fail-fast: false
       matrix:
@@ -36,34 +37,47 @@ jobs:
           - pg_version: 17
             arch: amd64
             runner: ubuntu-22.04
-    uses: ./.github/workflows/regress_tests_template.yml
-    with:
-      pg_version: ${{ matrix.pg_version }}
-      arch: ${{ matrix.arch }}
-      runner: ${{ matrix.runner }}
-      citus_version: 12
-
-  test-full:
-    if: github.event_name != 'pull_request'
-    strategy:
-      fail-fast: false
-      matrix:
-        pg_version:
-          - 15
-          - 16
-          - 17
-        arch:
-          - amd64
-          - arm64
-        include:
-          - arch: amd64
-            runner: ubuntu-22.04
-          - arch: arm64
+          - pg_version: 18
+            arch: arm64
             runner: ubuntu-22.04-arm
-    uses: ./.github/workflows/regress_tests_template.yml
-    with:
-      pg_version: ${{ matrix.pg_version }}
-      arch: ${{ matrix.arch }}
-      runner: ${{ matrix.runner }}
-      citus_version: 12
+    steps:
+    - name: Checkout repository
+      uses: actions/checkout@v4
 
+    - name: Build and Install DocumentDB
+      run: |
+        chmod +x ./scripts/build_documentdb_with_scripts.sh
+        ./scripts/build_documentdb_with_scripts.sh --pg-version ${{ matrix.pg_version }} --citus-version 12
+
+    - name: Export pg_config PATH
+      run: |
+        echo "/usr/lib/postgresql/${{ matrix.pg_version }}/bin" >> $GITHUB_PATH
+
+    - name: Run Tests
+      run: |
+        which pg_config    
+        export LC_ALL=en_US.UTF-8
+        export LANGUAGE=en_US
+        export LC_COLLATE=en_US.UTF-8
+        export LC_CTYPE=en_US.UTF-8
+        if [ "${{ matrix.pg_version }}" -eq 18 ]; then
+          make check-no-distributed
+        else
+          make check
+        fi
+
+    - name: Citus Indent
+      run: |
+        citus_indent --check || (echo ""; echo "citus_indent failed, refer to CONTRIBUTING.md on how to use citus_indent"; exit 1)
+
+    - name: Validate sanity of files
+      run: |
+        ./scripts/validate_extension_file_state.sh
+
+    - name: Upload Log Files
+      if: always() 
+      uses: actions/upload-artifact@v4
+      with:
+        name: logs_${{ matrix.arch }}_PG${{ matrix.pg_version }}
+        overwrite: true
+        path: "**/*.log"
